valory-xyz/contribution-service

- .gitignore
- packages/valory/skills/dynamic_nft_abci/models.py
- packages/valory/skills/dynamic_nft_abci/tests/test_models.py
[skip ci]
Ports the leaderborad read caching + locking functionality
n/a
> fix: porting caching  and locking mechanism

- README.md
- packages/packages.json
- packages/valory/agents/contribution/aea-config.yaml
- packages/valory/services/contribution/service.yaml
* Fix config error
* Small update to README
n/a
> fix: config

- packages/packages.json
- packages/valory/services/contribution/service.yaml
> feat: 4 agents

- packages/packages.json
- packages/valory/agents/contribution/aea-config.yaml
- packages/valory/services/contribution/service.yaml
- packages/valory/skills/contribution_abci/skill.yaml
> fix: add acn config

- HISTORY.md
Release 0.2.0
If it fixes a bug or resolves a feature request, be sure to link to that issue.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> Release 0.2.0

- mkdocs.yml
- scripts/check_doc_links.py
Fix wrong name in mkdocs.yaml
If it fixes a bug or resolves a feature request, be sure to link to that issue.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> Fix wrong name in mkdocs.yaml

- docs/index.md
- packages/packages.json
- packages/valory/agents/contribution/aea-config.yaml
- packages/valory/services/contribution/service.yaml
- packages/valory/skills/contribution_abci/skill.yaml
- scripts/check_doc_links.py
Add missing all_participants config
n/a
> fix: add all_participants

- .spelling
- HISTORY.md
- Makefile
> Release 0.2.0.post1

- Makefile
- docs/index.md
- packages/packages.json
- packages/valory/agents/contribution/aea-config.yaml
- packages/valory/services/contribution/service.yaml
- packages/valory/skills/contribution_abci/models.py
- packages/valory/skills/contribution_abci/skill.yaml
- packages/valory/skills/contribution_abci/tests/test_models.py
- packages/valory/skills/dynamic_nft_abci/skill.yaml
- tox.ini
* The chained abci tests where not being included in the test make target
* Fixes a failing test
* 100% coverage
* Recovers vulture
n/a
> fix: test, recover vulture

- docs/index.md
- packages/packages.json
- packages/valory/agents/contribution/aea-config.yaml
- packages/valory/contracts/dynamic_contribution/contract.py
- packages/valory/contracts/dynamic_contribution/contract.yaml
- packages/valory/services/contribution/service.yaml
- packages/valory/skills/contribution_abci/models.py
- packages/valory/skills/contribution_abci/skill.yaml
- packages/valory/skills/contribution_abci/tests/test_models.py
- packages/valory/skills/dynamic_nft_abci/skill.yaml
Splits the event retrieval into smaller requests
n/a
> fix: split events

- docs/index.md
- packages/packages.json
- packages/valory/agents/contribution/aea-config.yaml
- packages/valory/contracts/dynamic_contribution/contract.py
- packages/valory/contracts/dynamic_contribution/contract.yaml
- packages/valory/services/contribution/service.yaml
- packages/valory/skills/contribution_abci/skill.yaml
- packages/valory/skills/dynamic_nft_abci/behaviours.py
- packages/valory/skills/dynamic_nft_abci/rounds.py
- packages/valory/skills/dynamic_nft_abci/skill.yaml
- packages/valory/skills/dynamic_nft_abci/tests/test_behaviours.py
- packages/valory/skills/dynamic_nft_abci/tests/test_rounds.py
Remember latest parsed block to avoid retrieving all events during every period.
n/a
n/a
> fix: remember latest parsed block

- docs/index.md
- packages/packages.json
- packages/valory/agents/contribution/aea-config.yaml
- packages/valory/services/contribution/service.yaml
- packages/valory/skills/contribution_abci/skill.yaml
- packages/valory/skills/dynamic_nft_abci/behaviours.py
- packages/valory/skills/dynamic_nft_abci/skill.yaml
- packages/valory/skills/dynamic_nft_abci/tests/test_behaviours.py
- scripts/check_doc_links.py
> fix: timestamp

- Makefile
- docs/index.md
- packages/packages.json
- packages/valory/agents/contribution/aea-config.yaml
- packages/valory/agents/contribution/tests/test_contribution.py
- packages/valory/services/contribution/service.yaml
- packages/valory/skills/contribution_abci/skill.yaml
- packages/valory/skills/dynamic_nft_abci/behaviours.py
- packages/valory/skills/dynamic_nft_abci/models.py
- packages/valory/skills/dynamic_nft_abci/skill.yaml
- packages/valory/skills/dynamic_nft_abci/tests/test_behaviours.py
Remove the mock check from the dynamic_nft behaviour by changing how the url params are passed.
#25 
> fix: remove mock check

- docs/index.md
Updates the steps for the demo.
n/a
n/a
> Update steps in demo

- HISTORY.md
- SECURITY.md
Updates release history.
n/a
n/a
> chore: update history and security

- scripts/contribute_verify.py
Add a script to verify that the service is working properly by checking the image hashes it returns for every minted token and comparing them to the expected hashes.
```
(contribution-service) david@XPS13:~/Valory/repos/contribution-service$ python scripts/contribute_verify.py 
Loading token_to_address.json
Loading address_to_points.json
Loading token_to_hash.json
ID                    ADDRESS                        POINTS   EXP_IMAGE     IMAGE     OK
------------------------------------------------------------------------------------------
1    0x588d91aBF5192A0f0dc026bF05f510253bD1CF51       N/A    urfmcemm    urfmcemm   True
2    0x9F4e3422f5a701c887e1Eaa089f64395357Cd6Cb       N/A    urfmcemm    urfmcemm   True
3    0x3479Bf87C62D26B54943FADf3deB9826050f1de6       100    wpph776q …
```
> feat: verification script

- docs/index.md
Fix small display issue
If it fixes a bug or resolves a feature request, be sure to link to that issue.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> Fix small display issue

- .spelling
- HISTORY.md
- SECURITY.md
> chore: release 0.4.0

- .github/workflows/release.yaml
* Adds an extra tag to the docker image since the current release flow tags the image with the agent name, which is different from the service name.
n/a
n/a
> fix: extra release tag

- .github/workflows/release.yaml
* Fix workflow docker tag
n/a
n/a
> fix: workflow
